'use client';
import './globals.css'
import Head from './head'
import Navbar from "../components/Navbar"
import {SessionProvider} from "next-auth/react"; 
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Butterflies',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body>
      <SessionProvider>
        <Navbar />
        {children}
        </SessionProvider>
      </body>
    </html>
  )
}
